
#Client-only settings
[client]
	#Is position above HOTBAR (if false - use custom position)
	aboveHB = true
	#Inventory HUD position (X)
	#Range: 0 ~ 9999
	xPos = 0
	#Inventory HUD position (Y)
	#Range: 0 ~ 9999
	yPos = 0
	#Toggle on by default
	byDefault = true
	#Is Armor Damage HUD enabled
	ArmorDamage = false
	#Is Potions HUD enabled
	Potions = false
	#Potion HUD position (X)
	#Range: 0 ~ 9999
	xPotionPos = 0
	#Potion HUD position (Y)
	#Range: 0 ~ 9999
	yPotionPos = 0

