
#Client configuration settings
[client]

	#Configuration options for controller support (Must have Controllable install)
	[client.controller]
		#If true, will use the triggers on controller to control the acceleration of the vehicle.
		useTriggers = false

	#Configuration options for debugging vehicles
	[client.debug]
		#If true, renders an outline of all the elements on a vehicle's model. Useful for debugging interactions.
		renderOutlines = false
		#If true, the raytracer will be reloaded each tick.
		reloadRaytracerEachTick = false

	#Configuration for display related options
	[client.display]
		#If true, automatically switches to third person when mounting vehicles
		autoPerspective = true
		#If true, displays a speedometer on the HUD when driving a vehicle
		enabledSpeedometer = true
		#If true, an animation is performed while cycling vehicles in the workstation
		workstationAnimation = true

	#Configuration options for vehicle interaction
	[client.interaction]
		#If true, raytraces will be performed on nearby vehicles when left-clicking the mouse, rather than just right-clicking it. This allows one to be damaged/broken when clicking anywhere on it, rather than just on its bounding box.
		enabledLeftClick = true

